from __future__ import annotations

import re
from typing import Any, Dict, List, Tuple

import pandas as pd

from src.requirement_schema import CANDIDATE_FAMILY_TO_SCOPE_KEY, FACTOR_SCORE_COLUMNS


def _scope_family_key(material_family: str) -> str | None:
    value = str(material_family or "").strip()
    if value in CANDIDATE_FAMILY_TO_SCOPE_KEY:
        return CANDIDATE_FAMILY_TO_SCOPE_KEY[value]
    if "Ni-based" in value:
        return "Ni-based superalloy"
    if "Co-based" in value:
        return "Co-based alloy"
    if "Refractory" in value:
        return "Refractory alloy concept"
    if "Ti-alloy" in value or "Ti-based" in value:
        return "Ti alloy"
    if "Fe-Ni" in value:
        return "Fe-Ni alloy"
    return None


def _family_fit_score(material_family: str, requirements: Dict[str, Any]) -> float:
    """Prompt-sensitive family-prior score.

    This replaces the previous fixed Ni-first bonus with the deterministic family priors
    generated by scope_planner. It remains a downstream ranking signal only.
    """
    family_key = _scope_family_key(material_family)
    priors = dict(requirements.get("family_priors") or requirements.get("scope_plan", {}).get("family_priors", {}) or {})
    if family_key and priors:
        max_prior = max(priors.values()) if priors else 1.0
        if max_prior <= 0:
            max_prior = 1.0
        return round(10.0 * float(priors.get(family_key, 0.0)) / max_prior, 2)

    # Backward-compatible fallback for callers without schema/scope context.
    family = str(material_family or "")
    if "Ni-based" in family:
        return 8.0
    if "Co-based" in family:
        return 8.0
    if "Refractory" in family:
        return 7.5
    if "Ti-alloy" in family:
        return 7.0
    if "Fe-Ni" in family:
        return 6.0
    return 0.0


def _chemistry_fit_score(row: pd.Series) -> float:
    alloy_likeness = float(row.get("alloy_likeness_score", 0.0) or 0.0)
    n_elements = float(row.get("n_elements", 0.0) or 0.0)
    overlap = float(row.get("requested_overlap_score", 0.0) or 0.0)
    distinguishing_bonus = float(row.get("requested_distinguishing_bonus", 0.0) or 0.0)
    return round(alloy_likeness * 0.07 + n_elements * 1.10 + overlap * 1.25 + distinguishing_bonus * 1.6, 2)


def _active_factor_bonus(row: pd.Series, requirements: Dict[str, Any]) -> Tuple[float, str]:
    active_factors = list(requirements.get("active_factor_set") or requirements.get("scope_plan", {}).get("active_factor_set", []) or [])
    optional_factors = [
        factor for factor in active_factors
        if factor not in {"creep", "toughness", "temperature", "through_life_cost", "sustainability", "manufacturability", "route_suitability", "supply_risk", "evidence_maturity", "recipe_support"}
    ]
    if not optional_factors:
        return 0.0, ""

    weighted_excess = 0.0
    used = 0
    factor_weights = dict(requirements.get("active_factor_weights") or requirements.get("scope_plan", {}).get("active_factor_weights", {}) or {})
    reason_bits: List[str] = []
    for factor in optional_factors:
        score_col = FACTOR_SCORE_COLUMNS.get(factor)
        if not score_col or score_col not in row.index:
            continue
        score = float(row.get(score_col, 0.0) or 0.0)
        weight = float(factor_weights.get(factor, 0.20) or 0.20)
        if score >= 68.0:
            weighted_excess += (score - 68.0) * min(0.065, 0.035 + weight * 0.04)
            reason_bits.append(f"{factor.replace('_', ' ')} fit")
        elif score < 45.0:
            weighted_excess -= (45.0 - score) * 0.025
        used += 1
    if used <= 0:
        return 0.0, ""
    bonus = round(max(-2.5, min(4.0, weighted_excess)), 2)
    if bonus > 0 and reason_bits:
        return bonus, "prompt-specific " + ", ".join(reason_bits[:3])
    if bonus < 0:
        return bonus, "weak prompt-specific active-factor fit"
    return 0.0, ""


def _profile_bonus(row: pd.Series, profile_name: str) -> Tuple[float, List[str]]:
    bonus = 0.0
    reasons: List[str] = []

    if profile_name == "Performance-first":
        perf_bonus = max(0.0, (float(row.get("performance_summary_score", 0.0) or 0.0) - 70.0) * 0.12)
        bonus += perf_bonus
        if perf_bonus > 0:
            reasons.append("extra preference for stronger performance summary")

    elif profile_name == "Cost & sustainability-aware":
        combined = (
            float(row.get("through_life_cost_score", 0.0) or 0.0)
            + float(row.get("sustainability_score_v1", 0.0) or 0.0)
            + float(row.get("supply_risk_score", 0.0) or 0.0)
        ) / 3.0
        dec_bonus = max(0.0, (combined - 68.0) * 0.12)
        bonus += dec_bonus
        if dec_bonus > 0:
            reasons.append("extra preference for cost/sustainability/supply profile")

    elif profile_name == "AM route-first":
        route_bonus = max(0.0, (float(row.get("route_suitability_score", 0.0) or 0.0) - 68.0) * 0.18)
        bonus += route_bonus
        if route_bonus > 0:
            reasons.append("extra preference for preferred-route suitability")

    return round(bonus, 2), reasons


def _has_extreme_temperature_language(prompt: str) -> bool:
    prompt = str(prompt or "")
    return (
        any(
            term in prompt
            for term in [
                "extreme temperature",
                "extreme-temperature",
                "very high temperature",
                "very-high-temperature",
                "ultra high temperature",
                "ultra-high temperature",
                "ultra-high-temperature",
                "above 1000",
                ">1000",
                "1000°",
                "1050°",
                "1100°",
                "1150°",
                "1200°",
                "specialist processing",
            ]
        )
        or bool(re.search(r"(?:above|over|>|>=)\s*1[0-2]\d{2}\s*(?:°?c|celsius)?", prompt))
    )


def _is_engineering_analogue(row: pd.Series) -> bool:
    return str(row.get("candidate_source", "materials_project") or "materials_project") == "engineering_analogue"


def _service_intent_bonus(row: pd.Series, requirements: Dict[str, Any]) -> Tuple[float, str]:
    """Downstream service-intent bonus. This is not a survival filter.

    It prevents mature Ni/Co named analogues from automatically outranking refractory
    concepts when the interpreted design brief is explicitly extreme-temperature or
    refractory-led.
    """
    family_key = _scope_family_key(str(row.get("material_family", "")))
    temp = float(requirements.get("operating_temperature", 0) or 0)
    priors = dict(requirements.get("family_priors") or requirements.get("scope_plan", {}).get("family_priors", {}) or {})
    top_family = max(priors.items(), key=lambda item: item[1])[0] if priors else None
    schema = requirements.get("requirement_schema", {}) or {}
    inclusions = set((schema.get("hard_constraints", {}) or {}).get("family_inclusions", []) or [])
    prompt = str(schema.get("prompt_normalized", "") or "")
    candidate_is_seed = _is_engineering_analogue(row)

    explicit_refractory = (
        top_family == "Refractory alloy concept"
        or "Refractory alloy concept" in inclusions
        or "refractory" in prompt
        or "molybdenum" in prompt
        or "niobium" in prompt
        or "tantalum" in prompt
        or "tungsten" in prompt
        or _has_extreme_temperature_language(prompt)
        or temp >= 1050
    )

    bonus = 0.0
    reasons: List[str] = []

    if explicit_refractory and temp >= 1000:
        if family_key == "Refractory alloy concept":
            # Strong enough to overcome generic maturity/recipe advantages of Ni/Co named analogues.
            bonus += 24.0
            reasons.append("explicit >1000°C / refractory review favours refractory-family candidates")
        elif family_key in {"Ni-based superalloy", "Co-based alloy"}:
            bonus -= 8.0 if candidate_is_seed else -4.0
            reasons.append("kept as a comparison family under refractory-led service intent")
        elif family_key == "Ti alloy":
            bonus -= 10.0
            reasons.append("temperature is beyond normal titanium comfort zone")
    elif temp >= 1000:
        if family_key == "Refractory alloy concept":
            bonus += 12.0
            reasons.append("extreme-temperature service favours refractory capability")
        elif family_key == "Ti alloy":
            bonus -= 6.0
            reasons.append("temperature is beyond normal titanium comfort zone")

    if abs(bonus) < 0.01:
        return 0.0, ""
    return round(max(-12.0, min(26.0, bonus)), 2), "; ".join(dict.fromkeys(reasons))

def _recipe_bonus(row: pd.Series, requirements: Dict[str, Any]) -> Tuple[float, str]:
    recipe_mode = str(row.get("recipe_mode", "") or "")
    support = float(row.get("recipe_support_score", 0.0) or 0.0)
    matched = str(row.get("matched_alloy_name", "") or "").strip()
    family_key = _scope_family_key(str(row.get("material_family", "")))
    priors = dict(requirements.get("family_priors") or requirements.get("scope_plan", {}).get("family_priors", {}) or {})
    top_family = max(priors.items(), key=lambda item: item[1])[0] if priors else None
    schema = requirements.get("requirement_schema", {}) or {}
    prompt = str(schema.get("prompt_normalized", "") or "")
    temp = float(requirements.get("operating_temperature", 0) or 0)
    explicit_refractory_review = (
        top_family == "Refractory alloy concept"
        or "refractory" in prompt
        or _has_extreme_temperature_language(prompt)
        or temp >= 1050
    )

    if recipe_mode == "named_analogue":
        base_bonus = min(3.0, max(0.0, (support - 65.0) * 0.08))
        # In refractory-led reviews, named Ni/Co analogues should be useful comparison
        # references, not automatic winners purely because their recipe support is mature.
        if explicit_refractory_review and family_key != "Refractory alloy concept":
            base_bonus = min(base_bonus, 0.75)
            reason = (
                f"named {family_key} comparison reference ({matched})"
                if matched else f"named {family_key} comparison reference"
            )
        else:
            reason = f"named analogue-backed recipe support ({matched})" if matched else "named analogue-backed recipe support"
        return round(base_bonus, 2), reason if base_bonus > 0 else ""
    if recipe_mode == "analogue_guided":
        bonus = min(1.8, max(0.0, (support - 60.0) * 0.05))
        reason = f"analogue-guided manufacturing recipe ({matched})" if matched else "analogue-guided manufacturing recipe"
        return round(bonus, 2), reason if bonus > 0 else ""
    return 0.0, ""

def scientific_rerank(df: pd.DataFrame, requirements: Dict[str, Any]) -> pd.DataFrame:
    if df is None or len(df) == 0:
        return df

    out = df.copy()
    profile_name = requirements.get("downstream_profile_name", "Balanced")

    out["family_fit_score"] = out["material_family"].astype(str).apply(lambda value: _family_fit_score(value, requirements))
    out["chemistry_fit_score"] = out.apply(_chemistry_fit_score, axis=1)
    out["rerank_evidence_bonus"] = (out["evidence_maturity_score"].fillna(0) * 0.06).round(2)

    profile_bonus_values: List[float] = []
    profile_bonus_reason_values: List[str] = []
    recipe_bonus_values: List[float] = []
    recipe_bonus_reason_values: List[str] = []
    active_bonus_values: List[float] = []
    active_bonus_reason_values: List[str] = []
    service_bonus_values: List[float] = []
    service_bonus_reason_values: List[str] = []

    for _, row in out.iterrows():
        bonus, reasons = _profile_bonus(row, profile_name)
        profile_bonus_values.append(bonus)
        profile_bonus_reason_values.append("; ".join(reasons))

        recipe_bonus, recipe_reason = _recipe_bonus(row, requirements)
        recipe_bonus_values.append(recipe_bonus)
        recipe_bonus_reason_values.append(recipe_reason)

        active_bonus, active_reason = _active_factor_bonus(row, requirements)
        active_bonus_values.append(active_bonus)
        active_bonus_reason_values.append(active_reason)

        service_bonus, service_reason = _service_intent_bonus(row, requirements)
        service_bonus_values.append(service_bonus)
        service_bonus_reason_values.append(service_reason)

    out["profile_bonus"] = profile_bonus_values
    out["profile_bonus_reason"] = profile_bonus_reason_values
    out["recipe_rerank_bonus"] = recipe_bonus_values
    out["recipe_rerank_reason"] = recipe_bonus_reason_values
    out["active_factor_rerank_bonus"] = active_bonus_values
    out["active_factor_rerank_reason"] = active_bonus_reason_values
    out["service_intent_rerank_bonus"] = service_bonus_values
    out["service_intent_rerank_reason"] = service_bonus_reason_values

    out["scientific_rerank_score"] = (
        out["overall_score"]
        + out["family_fit_score"]
        + out["chemistry_fit_score"]
        + out["rerank_evidence_bonus"]
        + out["profile_bonus"]
        + out["recipe_rerank_bonus"]
        + out["active_factor_rerank_bonus"]
        + out["service_intent_rerank_bonus"]
    ).round(2)
    out["final_rank_score"] = out["scientific_rerank_score"]

    def rerank_reason(row: pd.Series) -> str:
        reasons = []
        if float(row.get("family_fit_score", 0.0) or 0.0) >= 8:
            reasons.append("strong prompt-specific family prior")
        if float(row.get("chemistry_fit_score", 0.0) or 0.0) >= 8:
            reasons.append("good chemistry-fit signal")
        if float(row.get("rerank_evidence_bonus", 0.0) or 0.0) >= 4:
            reasons.append("good evidence/maturity support")
        active_text = str(row.get("active_factor_rerank_reason", "") or "").strip()
        if active_text:
            reasons.append(active_text)
        service_text = str(row.get("service_intent_rerank_reason", "") or "").strip()
        if service_text:
            reasons.append(service_text)
        recipe_text = str(row.get("recipe_rerank_reason", "") or "").strip()
        if recipe_text:
            reasons.append(recipe_text)
        profile_text = str(row.get("profile_bonus_reason", "") or "").strip()
        if profile_text:
            reasons.append(profile_text)
        if not reasons:
            return "Ordered using the explicit downstream evaluation layer without any survival filtering."
        return "Ordered using " + "; ".join(reasons) + "."

    out["rerank_reason"] = out.apply(rerank_reason, axis=1)
    return out
